name: Test SqueakyCleanText

on: [push, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.7, 3.8, 3.9, 3.10, 3.11, 3.12]
                extras:
                    [
                        "",
                        "[dev]",  # Testing with dev extras
                    ]

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies with extras
              run: |
                python -m pip install --upgrade pip
                pip install .${{ matrix.extras }}
                pip install pytest

            - name: Download NLTK stopwords
              run: |
                nltk_downloader

            - name: Run tests
              run: pytest